<?php





<html>

<h1>HOLA</h1>
<body>

<h1>HOLA</h1>
    

<script> main.js </script>
</body>

    while
echo "<h1>"

</html>



client A                               SERVER (CHINA)


req =>                                      
                                         <= RESP     MPA





client A                                                    SERVER (CHINA)

    HTML 

    AJAX or FETCH  => REQ (POST,PUT,GET,DELETE) JSON    
                                                        <= RES JSON
                                                        
                                                        



JLIST 

+------------+
|            |
|            |   
+------------+


//

GET ALL SONG
GET SONG ARRAY (completed)
